version: "3.3"
services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/code/static
      - media:/code/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - proj_db



  proj_db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./_compose/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static/
      - media:/media/
    depends_on:
      - backend


volumes:
  static:
  media:
  postgres_data: