# Получить все голосования
GET localhost:80/votings
###

# Получить конкретное голосование
GET localhost:80/votings/1
###

#Проголосовать спешно("character_id": 9 или 10 (для перого голосования))
POST localhost:80/votings/1/vote/

{"character_id": 91}
###

# Вызвать исключение "Этот персонаж не участвует в голосовании" ("character_id": любой другой айди кроме 9, 10 )
# (для перого голосования)
POST localhost:80/votings/2/vote/

{"character_id": 1}
###


#Получить всех участников
GET localhost:80/characters/
###

#Получить победителя голосования
GET localhost:80/votings/2/retrieve_winner/