# Получить все голосования
GET localhost:8000/votings
###

# Получить конкретное голосование
GET localhost:8000/votings/1
###


#Проголосовать
POST localhost:8000/votings/6/vote/

{"character_id": 2}
###


#Получить всех участников
GET localhost:8000/characters/
###

#Получить победителя голосования
GET localhost:8000/votings/1/retrieve_winner/








