# Получить все голосования
GET localhost:8000/votings
###

# Получить конкретное голосование
GET localhost:8000/votings/1
###

#Проголосовать успешно("character_id": 9 или 10 (для перого голосования))
POST localhost:8000/votings/3/vote/

{"character_id": 8}
###

# Вызвать исключение "Этот персонаж не участвует в голосовании" ("character_id": любой другой айди кроме 9, 10 )
# (для перого голосования)
POST localhost:8000/votings/1/vote/

{"character_id": 9}
###


#Получить всех участников
GET localhost:8000/characters/
###

#Получить победителя голосования
GET localhost:8000/votings/1/retrieve_winner/







