# Получить все голосования
GET localhost:80/votings
###

# Получить конкретное голосование
GET localhost:80/votings/1
###


#Проголосовать
POST localhost:80/votings/1/vote/

{"character_id": 1}
###


#Получить всех участников
GET localhost:80/characters/
###

#Получить победителя голосования
GET localhost/votings/1/retrieve_winner/








